### ISSUE TITLE
ClassNotFoundException on launch

### ISSUE THREAD

**Issue by NetherDragonTw** [randomguy3725/MoonLight-public#7]
17:43:19.685
launcher
main
Using default game log configuration client-1.7.xml (outputs XML)
17:43:20.135
launcher
main
Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/opengl/OpenGLException
	at net.minecraft.client.main.Main.main(SourceFile:41)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.opengl.OpenGLException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more
17:43:20.136
monitor
Process Monitor
Process crashed with exit code 1

**Comment by AnaIytics** [comment]
how'd you fix it
